# Generated by Django 4.1.3 on 2024-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecepieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='recipe_name',
        ),
    ]
