# Generated by Django 4.1.3 on 2024-03-20 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecepieApp', '0002_rename_description_recipes_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
